name: Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make output directory
        run: mkdir output

      - name: Copy non-hidden files to output
        run: |
          shopt -s extglob
          cp -r !(.git|.*) output/

      - name: Compress non-hidden files
        run: |
          cd output
          zip -r ../archive.zip .

      - name: Upload archive.zip to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: non-hidden-files
          path: archive.zip

      - name: Upload hidden files (individually) to GitHub Artifacts
        run: |
          find . -maxdepth 1 -type f -name ".*" -exec echo {} \;

      - name: Upload hidden files to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hidden-files
          path: |
            .??*
